log_file: "logs/app.log"
rules:
  - name: "Organize Images"
    locations:
      - "/data/data/com.termux/files/home/storage/downloads/test"
    recursive: false
    filters:
      extensions: ["png", "jpg", "jpeg"]
      name:
        contains: ["car"]
    action:
      type: delete
      # destination: "/data/data/com.termux/files/home/storage/downloads/test/results"
      # over_ride: false
